language: node_js
node_js: stable
# Travis-CI Caching
cache:
  directories:
    - node_modules
# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install -g gulp

script:
  - gulp dist

after_script:
  - cd dist
  - git init
  - git config user.name "iissnan"
  - git config user.email "iissnan@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle