language: node_js
node_js: stable
# Travis-CI Caching
cache:
  directories:
    - node_modules
# S: Build Lifecycle
install:
  - npm install
script:
  - hexo clean
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "LinJieLinLin"
  - git config user.email "993353454@qq.com"
  - git add .
  - git commit -m "Update Blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_URL}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
  - secure: "gtTjsLor7/6tnMpuM0e4g8Om7A8KvZSd9uX1c9Ey4CyCpILEWpDyP/pEBM4e4gmt6ADierzWiDNlK76Vkprioql+RxVrRohu3VpEwDHWfNiRNY662ysLPqS8DVbWwJLsrPegdgyXd9WWkMaf49kwMRSWSpKh8dA0T6ngQqGaXKmJnlf6SQOZCZwucf33P+K2RqklAytnBDrVFUyKGmsk/qRbDu4mSVPlfIfBZktdPFm4tbyStTFw8PKixUD9b33SSbR4SeH5zYRCXzDIldTPL+fW2+yTWEM+g+WqTMZgRH/jJBsfGhjtjTW1Kb/c7hphpF/GoRl444Tm68LoGx7sTEhs7tCOAftEYShci5cMhRxxnuLiDJnzFUT9v4QIfaHyIHpTB+WTWCcFeaTmRcggoDaQbegkUReaUosw5V36YopdEVSMG0VL0V6WkQRaRfP6NrDBK6G5HjOTzc6qXUuxTfB6vYeT9sef0E3zEIHnVQBRl+uyeraRk5hBMeVCmjs1SoSFysdwzNhHCagM7PHWQSsWfwGZCa2X1e569SXxONF7WBF0C3iqCYHsWNa1LBC0YoESgMUp56yf/FiYauMoBa7isDs61jVBF2/bfOdfgRDrccjoLdHwuulb/3fRLs3PnqorAG0/Hmr/PazFwyw2IDlp7Psm9FbtumFaUJzg6OU="
